//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Base_Module
    {
        public string ModuleId { get; set; }
        public string ParentId { get; set; }
        public string Category { get; set; }
        public string Code { get; set; }
        public string FullName { get; set; }
        public string Icon { get; set; }
        public string Location { get; set; }
        public string Target { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> Isexpand { get; set; }
        public Nullable<int> AllowButton { get; set; }
        public Nullable<int> AllowView { get; set; }
        public Nullable<int> AllowForm { get; set; }
        public Nullable<int> Authority { get; set; }
        public Nullable<int> DataScope { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Enabled { get; set; }
        public Nullable<int> SortCode { get; set; }
        public Nullable<int> DeleteMark { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUserId { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUserId { get; set; }
        public string ModifyUserName { get; set; }
    }
}
