//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostRates
    {
        public System.Guid Id { get; set; }
        public string ReturnType { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string Store { get; set; }
        public string StoreNo { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUserName { get; set; }
        public string UpdateUserCode { get; set; }
    }
}
