//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecorationProgressMin
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> DecorationProgressMaxId { get; set; }
        public string MinName { get; set; }
        public Nullable<int> Sort { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
    }
}
