//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> OwnerFKId { get; set; }
        public Nullable<decimal> orderMoney { get; set; }
        public Nullable<decimal> rewardMoney { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> AuditState { get; set; }
        public string AuditUserName { get; set; }
        public string AuditUserCode { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public string AuditRemark { get; set; }
        public Nullable<System.Guid> UserFKId { get; set; }
        public string ImageStr { get; set; }
        public Nullable<System.DateTime> NextDate { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
