//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PictureMaintain
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string EditionType { get; set; }
        public string EditionTypeStr { get; set; }
        public string MaintainType { get; set; }
        public string MaintainTypeStr { get; set; }
        public string ImgUrl { get; set; }
        public string ImgUrl2 { get; set; }
        public string Remark1 { get; set; }
        public string Remark2 { get; set; }
        public string HttpUrl { get; set; }
        public string Other { get; set; }
    }
}
