//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ranks
    {
        public System.Guid Id { get; set; }
        public string UserName { get; set; }
        public string UserCode { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string RankTypeCode { get; set; }
        public string RankTypeName { get; set; }
        public string ImgUrl { get; set; }
        public string Remark { get; set; }
        public string Other { get; set; }
    }
}
