//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardExamine
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> UserFKId { get; set; }
        public Nullable<System.Guid> OwnerFKId { get; set; }
        public string RewardType { get; set; }
        public string RewardNode { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string StoreNo { get; set; }
        public string StoreName { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public string CreateUserCode { get; set; }
        public string CreateUserName { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string FinanceExamineRemark { get; set; }
        public string FinanceExamineStatus { get; set; }
        public Nullable<System.DateTime> FinanceExamineTime { get; set; }
        public string FinanceExamineUserCode { get; set; }
        public string FinanceExamineUserName { get; set; }
        public string BossExamineStatus { get; set; }
        public Nullable<System.DateTime> BossExamineTime { get; set; }
        public string BossExamineUserCode { get; set; }
        public string BossExamineUserName { get; set; }
        public string BossExamineRemark { get; set; }
        public Nullable<decimal> BossExamineMoney { get; set; }
        public string UserProp { get; set; }
    }
}
