//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardSets
    {
        public System.Guid Id { get; set; }
        public string RewardNode { get; set; }
        public string OperateRole { get; set; }
        public string RewardType { get; set; }
        public Nullable<decimal> DefaultMoney { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUserCode { get; set; }
        public string UpdateUserName { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
