//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendRecord
    {
        public System.Guid Id { get; set; }
        public string OpenId { get; set; }
        public Nullable<System.DateTime> ContentDate { get; set; }
        public string Content { get; set; }
        public string Type { get; set; }
        public string SendUser { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
