//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDeleteLogs
    {
        public System.Guid Id { get; set; }
        public string Openid { get; set; }
        public string NickName { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public string Store { get; set; }
        public string StoreNo { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string GuiderCode { get; set; }
        public string GuiderName { get; set; }
        public string GuiderTel { get; set; }
        public string DeleteUserCode { get; set; }
        public string DeleteUserName { get; set; }
    }
}
