//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Opinions = new HashSet<Opinions>();
            this.Owners = new HashSet<Owners>();
            this.ReferenceUsers = new HashSet<ReferenceUsers>();
            this.ReferenceUsers1 = new HashSet<ReferenceUsers>();
        }
    
        public System.Guid Id { get; set; }
        public string Openid { get; set; }
        public string NickName { get; set; }
        public string AvatarUrl { get; set; }
        public Nullable<int> Gender { get; set; }
        public string Name { get; set; }
        public string Tel { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string Store { get; set; }
        public string StoreNo { get; set; }
        public Nullable<System.Guid> StoreId { get; set; }
        public string Profession { get; set; }
        public string HeadImg { get; set; }
        public string ImgOne { get; set; }
        public string ImgTwo { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> AuditState { get; set; }
        public string AuditRemark { get; set; }
        public string AuditCode { get; set; }
        public string AuditName { get; set; }
        public string GuiderCode { get; set; }
        public string GuiderName { get; set; }
        public string GuiderTel { get; set; }
        public Nullable<System.DateTime> AuditDate { get; set; }
        public Nullable<int> Properties { get; set; }
        public string Trade { get; set; }
        public string IsSleep { get; set; }
        public string RealName { get; set; }
        public string CardNo { get; set; }
    
        public virtual ICollection<Opinions> Opinions { get; set; }
        public virtual ICollection<Owners> Owners { get; set; }
        public virtual ICollection<ReferenceUsers> ReferenceUsers { get; set; }
        public virtual ICollection<ReferenceUsers> ReferenceUsers1 { get; set; }
    }
}
