//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ZB
    {
        public string Name { get; set; }
        public string OwnerName { get; set; }
        public Nullable<decimal> Money { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Type { get; set; }
        public string District { get; set; }
    }
}
